### ISSUE TITLE
Remove parsl container bits

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#1013]
This issue is to remind us to remove Parsl container support and update the docs as soon as the funcX executor is integrated-- we should switch to recommending container support through it.

**Comment by benclifford** [comment]
Is this the same as removing IPP container support in PR #1558 ?

**Comment by yadudoc** [comment]
I do not think this is related to the IPP container support question. The issue here is that providers do not support containers well enough and were designed for the case where the managers/pilots were launched in containers simply by being invoked via say `docker run ...`. We can launch bash app's in containers if the command requested says `<container_flavor> run <some_command>`, but if we want python apps to run inside containers, we'll have to launch managers/workers inside containers. This latter situation is not well supported.

**Comment by yadudoc** [comment]
Now that bad docs are removed, let's come back to this post 1.0
