### ISSUE TITLE
htex/exex worker startup failure results in silent hangs

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1035]
Often I find that parsl cannot start the workers for htex or exex, with some error that is extremely obvious and diagnosable from the stderr of the worker pool program if run manually (for example, missing MPI or programmer error in syntax/imports).

These errors aren't straightfowardly presented to the user; instead often parsl seems to hang silently.

**Comment by hategan** [comment]
Outline of a partial solution that addresses the most common scenario: if no workers are running and three failures starting workers accumulate, fail all tasks queued on this executor.

**Comment by yadudoc** [comment]
If the executor.scale_out fails thrice consecutively trigger a failure over all tasks on the executor. We need to do this to let the layer above make decisions.

**Comment by hategan** [comment]
a small update: executor.scale_out rarely fails (e.g., it doesn't fail if process_worker_pool.py is missing), so this needs to be handled somewhere else

**Comment by hategan** [comment]
The "minimum of three failures" doesn't work when only two blocks are requested. This is what happens with my test case, which has init_blocks=2.

One could move the error checking code into the executor and have the executor decide that it should be a "minimum of init_blocks" failures instead of 3.

Thoughts?
