### ISSUE TITLE
Get the proper exception logs of a task when the task is retried

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#1105]
Looking at the code at https://github.com/Parsl/parsl/blob/185283452bafdd477a638c5882f259a962abf5d3/parsl/dataflow/dflow.py#L254, 

It does not seem to work. It is always `None`.
It would be great to get the exception so that we can log that to monitoring.db.

Probably related to #111.

**Comment by benclifford** [comment]
I suspect what is happening here is that the exceptions you are getting are returned inside RemoteExceptionWrapper as a regular result of the future, rather than as the future going into an exception state.

The code around line 245,

```
            res = future.result()
            if isinstance(res, RemoteExceptionWrapper):
                res.reraise()
```

ensures that if an exception arrives by the regular Future exception way, or by the RemoteExceptionWrapper mechanism, it will be raised as an exception; but only in the first way will `future` be storing an exception.

**Comment by benclifford** [comment]
Possibly catching the exception using `except Exception as e:` instead of just `except Exception` and using the newly bound variable `e` instead of `future._exception` will give you the value that you want in either exception handling path.
