### ISSUE TITLE
missing Flask on new Parsl install

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#1138]
On doing a fresh install of Swag, which requires Parsl, I get the following error:

```
Searching for Flask
Downloading https://files.pythonhosted.org/packages/9b/62/80a56f9d223f0b89cdcf7d592455375f8c9d73866f337fa85f39f45fe0c5/Flask-SQLAlchemy-2.4.0.tar.gz#sha256=0c9609b0d72871c540a7945ea559c8fdf5455192d2db67219509aed680a3d45a
Best match: Flask SQLAlchemy-2.4.0
Processing Flask-SQLAlchemy-2.4.0.tar.gz
Writing /tmp/easy_install-8akdu_kl/Flask-SQLAlchemy-2.4.0/setup.cfg
Running Flask-SQLAlchemy-2.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8akdu_kl/Flask-SQLAlchemy-2.4.0/egg-dist-tmp-39pas_5e
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
removing '/afs/crc.nd.edu/user/a/awoodard/.conda/envs/swag/lib/python3.7/site-packages/Flask_SQLAlchemy-2.4.0-py3.7.egg' (and everything under it)
Moving Flask_SQLAlchemy-2.4.0-py3.7.egg to /afs/crc.nd.edu/user/a/awoodard/.conda/envs/swag/lib/python3.7/site-packages
Flask-SQLAlchemy 2.4.0 is already the active version in easy-install.pth

Installed /afs/crc.nd.edu/user/a/awoodard/.conda/envs/swag/lib/python3.7/site-packages/Flask_SQLAlchemy-2.4.0-py3.7.egg
error: The 'Flask' distribution was not found and is required by parsl
```

**Comment by benclifford** [comment]
Do you have whatever is specifying the list of things to install, eg swag requirements.txt?

**Comment by annawoodard** [comment]
This does not work:
```
git clone https://github.com/PittGenomics/Swag
cd Swag
python3 setup.py install
```

This works:
```
git clone https://github.com/PittGenomics/Swag
cd Swag
pip install .
```

**Comment by benclifford** [comment]
Googling round for error messages like this, I've seen what looks like a lot of occurences of setup.py misresolving "Flask" to "Flask SomeOtherPackage" - eg Flask SQLAlchemy above, but in other bug reports `Flask WTF` (https://github.com/pypa/setuptools/issues/1013), or `Flask Login` (https://github.com/lingthio/Flask-User/issues/254).

It sounds like some bug in the setup stack, rather than in parsl

@ZhuozhaoLi also noted that he saw this when using `setup.py`

The `pip` based install is frequently tested in CI (every run) and hasn't shown this behaviour.

Hopefully using `pip` is a suitable workaround.

**Comment by benclifford** [comment]
I think this is a third-party bug in setuptools that there is a decent workaround for (as noted above). If so, maybe this issue should be closed? @annawoodard

**Comment by annawoodard** [comment]
Agreed
