### ISSUE TITLE
checkpointing vs parsl.AUTO_LOGNAME

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1293]
`parsl.AUTO_LOG_NAME` is resolved into a dynamically generated path before memoization happens. This means that an app invoked with `parsl.AUTO_LOG_NAME` will not be memoizable/checkpointable, as the arguments differ each time.

Maybe this resolution to a concrete path should be ignored by checkpointing: if an explicit stdout is specified, then it is reasonable to assume that the stdout/stderr really is an output; but if it is an automatic log name, it is debugging-style output and should not affect checkpointing.

**Comment by benclifford** [comment]
PR #1568 allows stdout/stderr to be ignored for memoization purposes. I've been using this in production for a few weeks and it works ok. This issue can be closed if/when #1568 is merged.

**Comment by annawoodard** [comment]
@benclifford I just got burned by this. Since there is no conceivable situation where a user would want `parsl.AUTO_LOGNAME` to make an app un-memoizable, what do you think about us adding `stdout` and `stderr` to `ignore_for_cache` automatically if `parsl.AUTO_LOGNAME` is set? Otherwise this is probable to result in significant time wasted for people who haven't studied the docs closely to debug the unexpected behavior.

**Comment by benclifford** [comment]
>  what do you think about us adding stdout and stderr to ignore_for_cache automatically if parsl.AUTO_LOGNAME is set? 

@annawoodard i think that's probably ok, in the sense of "deal with my stdout sensibly for me" rather than specifically "generate a filename"
