### ISSUE TITLE
Support job array type launcher for PBSPro

### ISSUE THREAD

**Issue by ravihansa3000** [Parsl/parsl#1576]
Submitting PBS job arrays would be efficient in some situations. For eg. in the NSCC environment, the wait time is too long for jobs submitted to the normal queue. However, NSCC favors jobs submitted as array jobs in two ways.

- Array jobs queue has a higher max_run limit; which means more jobs will get picked up that will run simultaneously.
- Array jobs are more likely to be picked up by the scheduler (in NSCC env), therefore, the wait time will be reduced.

Considering these factors, having a job array launcher for PBSPro provider would be very convenient.

**Comment by benclifford** [comment]
@ravihansa3000 do you have an example of what a submission for this would look like compared to what is being submitted at the moment?

**Comment by ravihansa3000** [comment]
Currently, PBSPro jobs are being submitted by Parsl as normal jobs [1]. I'm proposing to utilize job arrays [2] so that instead of submitting separate jobs for each block, an array job could be submitted. This behavior can be configurable via Parsl Config.

[1] https://github.com/Parsl/parsl/blob/master/parsl/providers/pbspro/template.py
[2] https://www.nas.nasa.gov/hecc/support/kb/using-job-arrays-to-group-related-jobs_464.html

**Comment by benclifford** [comment]
A block is at the parsl level a set of workers all submitted/managed together - so multiple blocks couldn't be submitted as a single array job, because all of an array job needs to be submitted at once.

But, a single parsl block could take the form of several smaller jobs inside one array job, rather than one large job - by adding an appropriate `-J` parameter into the submission template.

You could try that by adding in a `scheduler_options` parameter to `PBSProProvider()` with the extra lines to be inserted into the template.

**Comment by ravihansa3000** [comment]
Thanks for the suggestion.

I was able to run Parsl tasks as PBS array jobs using `scheduler_options` config param. 
`scheduler_options='#PBS -P xxxx \n#PBS -J 1-30',`
