### ISSUE TITLE
JobStatus objects failing equality checks

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1682]
**Describe the bug**
We need to be able to check the status returned from the `provider.status()` and that is currently not possible now, for eq:

```
>>> from parsl.providers.provider_base import JobState, JobStatus
>>> JobStatus(JobState.RUNNING) == JobStatus(JobState.RUNNING)
False
```

**Expected behavior**
We need at least equality and inequality to work for JobStatus

**Comment by hategan** [comment]
> **Describe the bug**
> We need to be able to check the status returned from the `provider.status()` and that is currently not possible now, for eq:

If by checking the status you mean figuring out if a job is in a particular state, then this assertion is incorrect.

> 
> ```
> >>> from parsl.providers.provider_base import JobState, JobStatus
> >>> JobStatus(JobState.RUNNING) == JobStatus(JobState.RUNNING)
> False
> ```

What you seem to want to do is JobStatus(JobState.RUNNING).state == JobStatus(JobState.RUNNING).state. Because JobStatus(JobState.RUNNING, message="a") == JobStatus(JobState.RUNNING, message="b") should not be True.

> 
> **Expected behavior**
> We need at least equality and inequality to work for JobStatus

Not really, because that equality is not well defined given that these can be complex objects that aren't always directly comparable. If you want to check the state, which seems to be the case given the example above, then compare those fields.

**Comment by benclifford** [comment]
I agree with @hategan that to test equality of `JobState`, `==` on `JobStatus` is the wrong thing to do.

**Comment by yadudoc** [comment]
Makes sense. I'm closing the issue and the PR.
