### ISSUE TITLE
Print name error when running in containers

### ISSUE THREAD

**Issue by ryanchard** [Parsl/parsl#177]
I am having an issue executing parsl apps within docker containers. Although this works correctly when executing the parsl app directly, it seems like the built-in python environment is being removed when I try to import the apps into another module and run it. For example, if I define a simple app that just prints "hello" in a file, say test.py, and invoke it directly (python test.py), everything works fine and the app is executed in my container. However, when I try to import test.py into another python script and execute it, I get an error that print is not defined. Here is a trace:

```
2018-03-30 11:07:32 parsl.dataflow.dflow:186 [ERROR]  Task 0 failed
Traceback (most recent call last):
  File "/home/ryan/Documents/Argonne/DLHub/parsl/parsl/dataflow/dflow.py", line 183, in handle_update
    future.result()
  File "/home/ryan/Documents/conda/anaconda3/envs/parsl/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/ryan/Documents/conda/anaconda3/envs/parsl/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ryan/Documents/conda/anaconda3/envs/parsl/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    raise r
ipyparallel.error.RemoteError: NameError(name 'print' is not defined)  File "/home/ryan/Documents/conda/anaconda3/envs/parsl/lib/python3.6/concurrent/futures/_base.py", line 432, in result
```

**Comment by yadudoc** [comment]
The issue here was that the wrapped apps were imported from a file which was not available on the containers. This resulted in the de-serialization failing, but continuing to the app execution phase instead of failing completely. The broken environment on the workers basically screwed the execution of the apps and returned a totally unrelated and unhelpful error.

To debug this, we enabled debug logging on the ipp workers, and inspected the logs.

The fix was to explicitly copy contents of the current directory to the containers.

**Comment by yadudoc** [comment]
Okay, there are some problems with that last commit.

1. Copying the current dir to the container image is surprising behavior.
2. Unnecessary and large data volumes might be gettting copied in
3. Sensitive information might get copied it.
4. We should be relying on the user building the image smartly
5. We are bound to miss some other python modules/packages coming from PYTHONPATH

So I'm rolling this back and adding a doc note.
