### ISSUE TITLE
How do I cancel a future ?

### ISSUE THREAD

**Issue by ssbehera-ncsu** [Parsl/parsl#2124]
Hi,

The cancel () function in AppFuture is not implemented yet.

raise NotImplementedError("Cancel not implemented")

Can you suggest a workaround to cancel a future launched via ThreadPoolExecutor ?

Regards,
Subhendu

**Comment by yadudoc** [comment]
Hi @ssbehera-ncsu, the `ThreadPoolExecutor` only supports cancel in a very limited context. In general most executors do not support task cancellation once execution has started. Here's a relevant snippet from the [docs](https://docs.python.org/3/library/concurrent.futures.html)

```
cancel()
Attempt to cancel the call. If the call is currently being executed or finished running and cannot be cancelled then the method will return False, otherwise the call will be cancelled and the method will return True.
```

I would appreciate some more detail on what your use-case here is? Often times, with longer running applications as is common in Parsl, `cancel()` is of little value since it cannot cancel running tasks, perhaps that is not a problem for you.

**Comment by ssbehera-ncsu** [comment]
Hi, Thanks for your reply!

In our workflow, we have a few execution stages which might get stuck because of algorithmic reasons. If cancellation doesn't seem feasible, is there a way to set a timeout value for a future or get the PID from the ThreadPoolExecutor. I think timeout/cancellation is a desirable, important feature for long running tasks.
