### ISSUE TITLE
Cannot get RSyncStaging to work

### ISSUE THREAD

**Issue by Oddant1** [Parsl/parsl#2179]
Hello all,

I have been attempting to use parsl to parallelize processes over heterogenous environments that do not share a file system. The case I have been testing is executing across my laptop and a remote server. I run parsl on my laptop and submit a job to the server. I then want to receive a file of results back from the server to be used on my laptop. 

Submitting the job to the server goes fine, and the job executes fine. I am trying to use RSyncStaging to get the results file back from the server to my laptop, but I have thus far been unsuccessful.

The code I have been attempting to run is below (with all ips anonymized). When I attempt to get the result at the end, I get the below error on my laptop's end. I'm not sure how to use the RSyncStaging provider at all, and any help is appreciated. 

Thank you.

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/out.txt'
```

```
import psutil

import parsl
from parsl.config import Config
from parsl.providers import AdHocProvider
from parsl.executors.threads import ThreadPoolExecutor
from parsl.executors import HighThroughputExecutor
from parsl.data_provider.rsync import RSyncStaging
from parsl.data_provider.file_noop import NoOpFileStaging
from parsl.app.app import python_app
from parsl.data_provider.files import File

parsl.load(Config(
    executors=[       
        ThreadPoolExecutor(
            storage_access=[NoOpFileStaging(), RSyncStaging('server_ip')],
            
            max_threads=max(psutil.cpu_count() - 1, 1),
            label='default'
        ),
        HighThroughputExecutor(
            label='remote_htex',
            max_workers=6,
            worker_logdir_root='./parsl/logs',
            storage_access=[NoOpFileStaging(), RSyncStaging('laptop_ip')],

            provider=AdHocProvider(
                # Command to be run before starting a worker, such as:
                # 'module load Anaconda; source activate parsl_env'.
                worker_init='load my conda env',
                channels=[parsl.channels.SSHChannel(
                    hostname='server_ip', username='uname',
                    script_dir='./parsl/scripts')]
            )
        )
    ],
    #  AdHoc Clusters should not be setup with scaling strategy.
    strategy=None,
))

@python_app(executors=['remote_htex'])
def remote_func(inputs=[], outputs=[]):
    with open(outputs[0].filepath, 'w') as fh:
        fh.write('Some stuff')

@python_app(executors=['default'])
def func(inputs=[]):
    with open(inputs[0].filepath, 'r') as fh:
        return fh.readline()
        
f = File('file:///tmp/out.txt')
future = remote_func(outputs=[f])
future2 = func(inputs=[future.outputs[0]])

future2.result()
```

**Comment by benclifford** [comment]
The `storage_access=` definitions look wrong to me.

`storage_access` defines how file:// URLs referring to your submitting system filesystem can be made available on the relevant executor's filesystem (and vice-versa, how a file visible to the executor can be made visible on the submit side).

For the ThreadPoolExecutor, this is a trivial operation, because the ThreadPoolExecutor shares the same filesystem as the submitting code. so for that executor you should define just `storage_access=[NoOpFileStaging()]`. NoOpFileStaging means "don't do any staging as the file will already be in the right place."

For the remote htex executor, you have configured both the NoOpFileStaging method and the RSync method which both handle file URLs; so the first, NoOpFileStaging, will take precedence. This is the wrong behaviour: that is telling parsl that a file on your submitting system will automatically be visible on the executor (and vice versa) and that parsl doesn't need to do any staging activity.

So for your htex executor definition, remove NoOpFileStaging and leave RSyncStaging. This will then tell parsl that, in order for a file to be visible on the remote system from the local system (and vice-versa), rsync must be used.

**Comment by Oddant1** [comment]
Thank you @benclifford for clarifying that. After removing NoOp, the RSyncStaging is now working. Basically, both RSync and NoOp were trying to handle the same files, and since NoOp was first it was taking precedence over RSync?

**Comment by benclifford** [comment]
> since NoOp was first it was taking precedence over RSync?

yes - what happens is each staging provider is offered each file in turn, until one of them claims it can stage it.

So, for example, the http staging providers will not claim to support `file:` URLs, for example.
