### ISSUE TITLE
Parsl internal bugs silently squashed then hangs

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#240]
@benclifford reported an alarming bug in which a error in the parsl code does not throw an exception but is silently squashed. This is followed by the code hanging and not making progress. To make the situation even worse the strategy thread continues to run, giving the impression that parsl is doing something. 

My suspicion is the the exception silently kills some thread, and that goes unreported.

The string formatting bug added here (in memoization code) -> https://github.com/Parsl/parsl/tree/pr238-related-example reproduces this issue with a test script that hits this memoization code. 

Some recommendations:
1. Better exception handling
2. Logs to show thread-ids so that we can see when threads have gone missing

**Comment by benclifford** [comment]
I had a bit of a poke with stack traces, and I think exceptions thrown inside a future callback such as `handle_update` probably hit this:

https://docs.python.org/3/library/concurrent.futures.html

> If the callable raises an Exception subclass, it will be logged and ignored.

**Comment by benclifford** [comment]
... and indeed with more logging turned on by this: (to log everything, not just parsl logs)

```
parsl.set_stream_logger(name=None)
```

... I see this message now on the log output:

```
2018-05-21 12:00:11 concurrent.futures:299 [ERROR]  exception calling callback for <Future at 0x7ff1dd136cf8 state=finished returned int>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 235, in handle_update
    self.checkpoint(tasks=[task_id])
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 629, in checkpoint
    raise ValueError("BENC: deliberate checkpoint failure")
ValueError: BENC: deliberate checkpoint failure
```

A short term workaround might be to attach logging to `concurrent.futures` so that we can see this as log output; it doesn't fix the broader problem of parsl ignoring the exception.

**Comment by annawoodard** [comment]
We shouldn't consider this issue fixed yet. I think @benclifford inadvertently closed the issue by saying the issue wasn't fixed 😄.

**Comment by benclifford** [comment]
We should be clear about where the error should go.

Perhaps:
If it is related to an unfinished future, it should pop out at the point you wait/inspect the final value of the future.
If it is otherwise related, it should pop out at DFK cleanup (or in non-lazy error mode, however errors should manifest, which I'm a bit unclear on).

**Comment by yadudoc** [comment]
I don't think this is a problem anymore. We can re-open if we find that this is still unresolved.
