### ISSUE TITLE
Warn on version mismatches

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#244]
Reported by @ahayschi and @reidmcy

We should check for version mismatches and raise an error under certain circumstances. Related to #228.

**Comment by yadudoc** [comment]
The version information is now captured from the managers and returned to the interchange. We should decide if it is okay to have this information go into the interchange logs or float back to the executor. The obvious route would be to have this information return via the status command to report a manager in an exceptional state due to version mismatch.
