### ISSUE TITLE
HTEX Manager does not handle SIGTERM

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#2956]
**Describe the bug**

The HTEX manager does not have a handler for SIGTERM. Currently, if the manager dies the workers become orphaned and end up just hanging about without terminating. 

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Run the following code:
``` python
@python_app
def kill_manager():
      import os, signal
      os.kill(os.getppid(), signal.SIGTERM)
```

**Expected behavior**
Manager should terminate all workers when shutting down.

**Comment by benclifford** [comment]
Also look at this from the perspective of the manager going away without getting a chance to run its handler - eg if it is SIGKILLed by some mysterious entity. That maybe means that workers should shut down when their other-end (the manager) is gone away: crossref #2742

See Erlang-style "this process will die if this other process died" behaviour.

All of the "make sure we carefully orchestrate shutdowns across processes in this particular sequence" protocols we've had in Parsl have turned out to be quite awkward to verify and debug.

**Comment by yadudoc** [comment]
Had a chat with @rjmello, he'll be taking a stab at this.
