### ISSUE TITLE
Applications using TaskVine and WorkQueue executors do not exit

### ISSUE THREAD

**Issue by colinthomas-z80** [Parsl/parsl#3251]
**Describe the bug**
Applications using TaskVine and WorkQueue executors do not exit.

The last two daily tests have failed https://github.com/cooperative-computing-lab/cctools-packaging-test/actions

It appears this bug was introducted in #3165 , now the dfk().cleanup() is not called in the atexit handler. 

**To Reproduce**
1. Run a taskvine or work queue app using parsl after e11eef4.
2. Observe the program will finish all tasks however it will not exit.

**Expected behavior**
An application should exit when the main python process is done.

**Environment**
 - Python version python-3.11.8
 - Parsl version parsl-2024.3.11

**Comment by colinthomas-z80** [comment]
I see the discussion in #3104. It seems our executors have been relying on this exit. I am looking to see how exactly a program using HTEX decides it is time to cleanup.

**Comment by benclifford** [comment]
@colinthomas-z80 plenty of code relies on dfk.cleanup() being called, not just taskvine and wq - but as of #3165, it is now up to the user to do so (because Python >=3.12 gets upset at various cleanup operations being called in atexit).

You should see in the main parsl test server that WQ and taskvine tests do exit OK without hanging (otherwise, we could not have merged that PR #3165) - but it's now an obligation on the user to clean up properly rather than letting `atexit` do it.

It looks like you added that cleanup to the cctools test suite here: https://github.com/cooperative-computing-lab/cctools-packaging-test/commit/12a83576033af941a8d3f0bd0d7586b0cbd4f2cf

I'd like this to look a bit nicer for users, for example, instead of writing a load and cleanup pair, instead possibly use a `with` block so that cleanup can happen that way - that's a pretty Pythonic way of dealing with this allocate/cleanup behaviour, so I'd like to give users a way to do that.

For wq/taskvine hanging at exit, I've been working on other parts of the parsl codebase for a looooong time trying to discover all the different ways hangs can happen at shutdown, especially shutdowns where processes disappear in a surprising order (most commonly: when someone sends a SIGTERM or hits ctrl-C, or when the kernel Out Of Memory Killer decides to reap one of the Parsl processes. This is frustratingly subtle and irrelevant to the traditional core goal of actually running tasks. Generally those hangs have been happening when processes or threads assume that some other process will come along to tell them to shutdown, and that if shutdown happens some other weird way, they mistakenly should stick around forever waiting for the shutdown signal that never comes. For threads, one thing I've done sometimes is mark a thread as `daemon` - if it's safe for the thread to just disappear at shutdown time.

and in that context...

> I am looking to see how exactly a program using HTEX decides it is time to cleanup.

there are plenty of situations where it *doesn't*. Have a look at the safe exit issues tag for examples: https://github.com/Parsl/parsl/issues?q=is%3Aissue+is%3Aopen+label%3Asafe-exit

**Comment by colinthomas-z80** [comment]
Satisfied by #3269
