### ISSUE TITLE
fatal: Not a git repository: '/homes/vvikraman/anaconda3/lib/python3.6/site-packages/.git

### ISSUE THREAD

**Issue by vvinuv** [Parsl/parsl#326]
Hi 
When I try to run parsl I am getting the following issue:

fatal: Not a git repository: '/homes/vvikraman/anaconda3/lib/python3.6/site-packages/.git

Is it a real issue?

I am using python3 and jupyter but run parsl in a terminal.

**Comment by yadudoc** [comment]
Parsl tries to check and report the git version in case the user is trying to use parsl from source. This is non-fatal and should not affect workflow execution in any way.
We'll have this cleaned up in the next release.

**Comment by annawoodard** [comment]
Thanks for the report, @vvinuv! As @yadudoc says, the issue here is that the error message is confusing-- the error itself does not affect workflow execution. It just means that we cannot determine if you've modified the parsl code. In the next release we will not print the traceback, since it is confusing.
