### ISSUE TITLE
Create a glossary of terms for Parsl documentation

### ISSUE THREAD

**Issue by WardLT** [Parsl/parsl#3426]
**Is your feature request related to a problem? Please describe.**
The many workflow systems vary in terminology they use, and Parsl is not special of this. We should create a Glossary for terms and make it prominent in the documentation for key concepts, such as:

- [x] Block
- [x] App
- [ ] Job
- [ ] Worker
- [x] Executor

**Describe the solution you'd like**
A documentation page with one sentence explanations for each term.

**Describe alternatives you've considered**
Linking people to the Quickstart, where I've tried to explain each term. However, the narrative form of that document is not great for quick reference.

**Additional context**
This would be great for our Outreachy team member :D

**Comment by benclifford** [comment]
cc @sophie-bui

**Comment by benclifford** [comment]
other concepts i've found poorly separated:

* task
* (worker) pool
* manager (of workers)
* app invocation - vs task, vs (definition of an) app

**Comment by benclifford** [comment]
* node

... is a great one because it has two completely different meanings: node in the graph-theory sense of a piece of a DAG, if you have DAG-brain engaged; and something similar to what Internet Protocol people would call a __host__ that executes code. for example, disambiguate this: a node is executed on a node.


* resource

this gets loosely used in the same way that people use the word __asset__ elsewhere - often to mean not much more than "thing".
