### ISSUE TITLE
Parsl hangs when using MPI Mode HTEx if resource specs are not found

### ISSUE THREAD

**Issue by WardLT** [Parsl/parsl#3427]
**Describe the bug**
I found, accidentally, that Parsl will hang if a task is sent to HTEx running in "MPI Mode" if you fail to provide a `parsl_resource_dict` as an explicitly-named keyword argument.

It appears that the the resource requirements are not sent along with the task if you provide the resource specification as a keyword argument. 
The lack of task records means that the task is not registered in the `tasks_to_nodes` map in `MPIScheduler` and therefore not found when the last completes.

```
2024-05-13 12:07:17.349 parsl:409 8518 Result-Pusher [ERROR]  Got an exception: 1
Traceback (most recent call last):
  File "/home/lward/Work/ExaLearn/parsl/parsl/executors/high_throughput/process_worker_pool.py", line 403, in push_results
    r = self.task_scheduler.get_result(block=True, timeout=push_poll_period)
  File "/home/lward/Work/ExaLearn/parsl/parsl/executors/high_throughput/mpi_resource_management.py", line 213, in get_result
    nodes_to_reallocate = self._map_tasks_to_nodes[task_id]
KeyError: 1
```

**To Reproduce**

Remove the `parsl_resource_requirements` from the input arguments to an MPI app in any of the tests.

**Expected behavior**

Parsl at least fails with an error message, at least. It might be good for Parsl to substitute some default values (1 rank per node, 1 node) with a warning so that tasks still run.

**Environment**
 - OS: Ubuntu
 - Python version: 
 - Parsl version: `master` as of today.

**Distributed Environment**
- Where are you running the Parsl script from ? Desktop
- Where do you need the workers to run ? Same as parsl

**Comment by R1j1t** [comment]
If it's not an urgent fix, I can work on this over the weekend!

**Comment by benclifford** [comment]
@R1j1t I think there are two things going on here. I think you should only try to fix the first one at first, in one PR. You might like to try the second one too, but it is much more subtle (and perhaps controversial), so if you attempt that, you should do that in a separate PR.

One part (perhaps easiest) is to make sure that at submit time (in `HighThroughputExecutor.submit`, perhaps, where it is very easy to fail) that if enable_mpi_mode is set, then validate the resource specs that are expected, and raise an exception right away if they are not. This is a good piece of the code to raise an exception, because it will result in that exception being handed back to the user pretty cleanly - so the user can quite easily see the explanation you are giving in the exception text.

One part, which is more architectural and more subtle, is that exceptions happening in some places will cause Parsl to hang because they do not correctly turn into a top level Parsl failure in the submitting process: for example, if the process worker pool `ResultPusher` thread gets an exception of any kind during the get result section, the code logs an exception and then does nothing else to converge towards a result.

I suspect that might be because sometimes, in not-encrypted mode, the worker pool gets random connections from elsewhere and tries to process those as results. That failure mode is more safely dealt with by turning on `encryption=True` (introduced in PR #3030) and maybe we should not be trying to ignore bad stuff happening at this layer any more. In which case, we can adopt an Erlang/OTP inspired approach and exit the process worker pool entirely. This will propagate failure of that task (and all others) upwards towards the user (at the expense of killing other tasks being performed by that worker pool).

**Comment by benclifford** [comment]
> If it's not an urgent fix, I can work on this over the weekend!

This is not urgent -- this MPI work is an ongoing prototype that needs thoughtful fixes rather than hurried fixes.

**Comment by R1j1t** [comment]
Thanks @benclifford for the information. I will look into these suggestions in context of the codebase once I start, but your comments have already made my learning curve much smoother!
