### ISSUE TITLE
Support for shifter on NERSC

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#417]
Our current container model does not adequately capture the tight integration shifter has with the scheduler launch mechanism. From the docs here : (http://www.nersc.gov/users/software/using-shifter-and-docker/using-shifter-at-nersc/) it looks like the SlurmProvider would need to be updated to be more container aware.

**Comment by benclifford** [comment]
I've succesfully run shifter in two different modes on cori: In one mode, I run bash apps which contain a shifter command line, so that there is one shifter container per app. In another mode, I implement a workflow specific launcher which puts an appropriate shifter container commandline around process worker pool. Brief documentation on this second approach was added in #1263.

I think this does not need any further core parsl work, so I'm closing this.
