### ISSUE TITLE
Support for containers

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#45]
Support for running applications in containers. Make this a high level app type. Investigate support for reusing cached containers. Investigate support for containers as a sandbox. 

Potentially we would want to support different container models for different systems. We'd want to define a single app that could then use different containers on each system. 

Perhaps something like the following: 

app('container', dfk):
def foo(param1, param2):
    return {singularity :  {container-uri: uri, config: foo, run: "param1 param2"},
                docker: {container-uri: uri, config: foo, run: "param1 param2"}}

Maybe better to wrap each container type as its own class?

**Comment by yadudoc** [comment]
Pushing to 0.6.0

**Comment by yadudoc** [comment]
As an intermediate step, we will add support for launching IPP engines within containers. By specifying specific sites that use a particular container, and tying apps to those site, you can execute apps within containers that support them.

**Comment by yadudoc** [comment]
0.5.0 added minimal container support. This was done in the IPP executor, by having the ipengine calls wrapped by container calls. This approach however works **only** when ddocker containers can be launched directly for eg. on a node with docker available. We need this this logic to be pushed down to libsubmit so that containers are launched in a way suitable to the compute resource, (say Kubernetes).

@annawoodard  This is additional work that needs to happen in order to support containers properly.
