### ISSUE TITLE
Imsim run issues

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#501]
From @benclifford 

- [ ] i) parsl/mpix ability to survive task memory explosion
- [ ] ii) imsim memory explosion
- [ ] iii) timescale for that extra implementation of that extra output stuff that needs checkpoints to be kept around
- [ ] iv) if [iii] is a long time, then ability to prune work some other way than checking if checkpoints are deleted
- [ ] v) ability of parsl to run this workflow in "long term" mode (over 10 days, for example)

**Comment by benclifford** [comment]
> ii) Could @benclifford clarify how this is different from i)

i) is making parsl more useful as a tool for understanding possibly-misbehaving application code in general

ii) is understand this particular piece of application code

**Comment by yadudoc** [comment]
At the point this issue was made, we were running MPIX which is prone to single node failures bringing down the whole 1K+ node job. This comes from fault tolerance limitations in MPI. To workaround this HTEX uses zmq for all communication, meaning task failures will only terminate and block execution on a limited # of nodes within a large batch job. 

We've not made any progress on trapping/containing the OOM error, but we've added monitoring that would allow the user to identify the app and it's memory use pattern that led to the failure. So, we can help with diagnosing the issue but not automatically contain it. With fixes to imsim code, containment is  no longer a priority.

v) is still a major pain point. HTEX/EXEX are capable of fair task distribution, fault detection allowing multi-job/day campaigns to run smoothly. However we still have difficulty protecting against login node termination which can bring down the parsl client and interchange processes. We've got two potential solutions here, 1) Submit the entire workflow as a job, so that we are not dependent on the login nodes (#643) 2) Run from a workflow host outside the facility like AWS. (#775)

Most of the issues listed here are addressed and the remaining ones are lower priority issues being tracked separately, so I'm closing this one.
