### ISSUE TITLE
Automatic retry for failed apps

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#63]
In many failure cases Parsl could retry an app within some given parameters.  We need to develop a model for specifying retry logic and representing different failure modes in parsl (e.g., app failure vs system failure). 

Dominic and others have requested this feature.

**Comment by annawoodard** [comment]
Another way to categorize failures, which unfortunately is not always straightforward to tease out: transient (i.e., where a retry is helpful) vs non-transient failures. Recognizing all the different failure modes automatically is something we should aim for, but a pretty ambitious project, and the parameter space of unintentional consequences is really large. I vote to be somewhat conservative at first, at least. Sometimes the user in the best position to know transient vs non-transient, so one low-hanging fruit simplified starting point would be to allow the user to specify a mapping of particular exception classes or exit codes to number of retries. (Obviously this is just syntactic sugar for what the user could implement themselves, but I think that's what a lot of people have in mind when they ask for the feature).

**Comment by annawoodard** [comment]
I'm not familiar with Parsl enough yet to know if this is something that comes up often, but I imagine that there is a class of site-specific errors. In that case it could be useful to allow users to specify a 'blacklist' such that an app returning the mapped exception classes/exit codes would automatically be blacklisted from that site and tried on alternatives.

**Comment by kylechard** [comment]
Completely agree. I think providing a simple way for users to declare when apps should be re-run would be great. It would be nice if we had a set of well defined error classes that they could use to specify this behavior. We'll definitely want to plug this logic into the multi-site model so that users could include blacklist-like rules too.

**Comment by yadudoc** [comment]
I have a minimal working solution of this working on the retires_#63 branch. In this simplified implementation, the user specified failRetries=N and, whenever an app fails, Parsl retires the app upto a maximum of N times.

There are some issues here that I would like input on:
1. We report failures in the log, but do we want expose exception history to the user via exceptions?
2. failRetries sound bad, maybe maxRetries is better ?
3. I'm assuming that is lazyFailure is set to false, retries won't kick in, and the app fails immediately.
4. Retries are a global setting, that applies to all apps
5. We don't differentiate between failure types in retries.

**Comment by annawoodard** [comment]
There are a few things that aren't clear to me from skimming this, so I'm just going to ask, rather than dig in. Sorry for being lazy! Can you clarify why both `lazy_fail` and `failRetries` is needed? Understanding the meaning of each additional option is extra cognitive load on the users, so we should minimize them if possible. Why not just have one argument, say `retries`, which defaults to zero (and if zero indicates no retries are allowed)?

So instead of:
```Python
            try:
                future.result()
            except Exception as e:
                logger.info("Task[{}]: FAILED with [{}]".format(task_id, e))

                self.tasks[task_id]['fail_count'] += 1

                if not self.lazy_fail:
                    logger.debug("Eager fail, skipping retry logic")
                    raise e

                if self.tasks[task_id]['fail_count'] <= self.fail_retries:
                    logger.debug("Task[{0}]: Retrying".format(task_id))
                    # Set tasks for a retry
                    self.tasks[task_id]['status'] = States.pending

                else:
                    logger.info("Task[{0}]: All retry attempts:{1} have failed".format(task_id,
                                                                                        self.fail_retries))
                    self.tasks[task_id]['status'] = States.failed
```

Consider:
```Python
            try:
                future.result()
            except Exception as e:
                logger.info("Task {} failed with: {}".format(task_id, e))

                self.tasks[task_id]['fail_count'] += 1

                if self.tasks[task_id]['fail_count'] > self.retries:
                    logger.debug("Task {} failed".format(task_id))
                    self.tasks[task_id]['status'] = States.failed
                    raise e
                else:
                    logger.debug("Retrying task {}".format(task_id))
                    self.tasks[task_id]['status'] = States.pending

```
The second version does not differentiate between the case where the retries have run out, and the case where retries were forbidden from the start-- but I'm not sure how useful that information is, since the previous retries will have been logged. In any case, if you want to retain the differentiation, but remove the need for the `lazy_fail` option, you could keep the first version, but change `if not self.lazy_fail:` -> `if self.retries == 0:`.

As to your points:
1. I don't follow, can you clarify?
2. Is `fail` or `max` necessary, would simply `retries` be sufficient?
3. My strong preference would be to allow setting retries per-app rather than only globally.
4. I think it is reasonable not to differentiate between failure types in the first iteration, and open separate issues as needed to describe and discuss more sophisticated features.

**Comment by annawoodard** [comment]
Note another minor opinion, I prefer:
```
                logger.info("Task {} failed with: {}".format(task_id, e))
```
to
```
                logger.info("Task[{}]: FAILED with [{}]".format(task_id, e)).
```

`Foo[bar]` looks like a python dictionary, so I think it is preferable to omit the square brackets, which might be confusing. Also, the colon is not serving a critical function in the latter case; in the former case it allows you to omit the square brackets and retain differentiation between the logging message and the exception message.

**Comment by yadudoc** [comment]
When lazy_fail is True, we allow the workflow to continue until no further progress can be made. Lazy fail is used often during development, when you want the workflow to stop as soon as your encounter an issue. LazyFail handles workflow resiliency whereas Retries is about App resiliency. We need both.
I'll update naming to lazyFail for consistency. 

1. If an application fails with different errors during each retry, that might be interesting to the user. We can provide a longer traceback, but I worry that it won't be helpful.
2. We need both. Naming wise fail_retries -> retries is simpler
3. I know, this is an initial cut to test out functionality. I'll add this once this is well tested.
4. Agreed.

We should move any discussion on log lines to #85 .  My goal with log lines is to have something that looks like <TASK_ID> <general update> <Additional details>. This is easier on the eyes, and makes it easy to grep by task.

**Comment by annawoodard** [comment]
Thanks for the explanation! That makes sense. Sorry for my long comment which I now see is irrelevant 😄.  In that case, I vote to clarify the docstring, instead of:
```
lazy_fail(Bool) : Default=True, determine failure behavior
```
consider (I'm switching to the opposite because it's easier for me to describe, but you could tweak this to stay with `lazy_fail` instead of `eager_fail`):
```
eager_fail(Bool) : Default=False, If any app raises an exception, immediately re-raise it to halt the DataFlowKernel
```
1. I think 10000000% whatever exceptions the user is getting needs to be reported somewhere. I'm still not quite following though. Is the choice: should we report exceptions in the logs or not?  Or: should we report the full traceback in the logs or not? If you're worried the traceback is too verbose it could just be reported at a higher verbosity level.
2. Just to clarify, you are agreeing to change `failRetries` to `retries`?
3. Awesome!
