### ISSUE TITLE
Quoting consistency in docs

### ISSUE THREAD

**Issue by jmjwozniak** [Parsl/parsl#67]
Do we have a standard for single/double quotes?  For example, see the code snippet here: http://parsl.readthedocs.io/en/latest/userguide/data.html

**Comment by yadudoc** [comment]
We don't, but we should and I need to get the docs to conform. Thanks for catching this :)

Here's what I'll do : 
1. Update all user docs to use single quotes unless the situation demands double quotes, say quoting a specific bash string.
2. Follow PEP257/PEP8 recommendation to use triple double quotes instead of triple single quotes for docstrings.
