### ISSUE TITLE
LowLatency Executor: interchange.log not saved in rundir

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#744]
We need to move interchange.log to rundir.

**Comment by yadudoc** [comment]
@rohankumar1998 Can you take a look at this ?

**Comment by rohankumar1998** [comment]
Where in the rundir do you think is best? `rundir/interchange.log`?

**Comment by yadudoc** [comment]
Since we could have multiple executors in the same run, we want it to go to `<rundir>/<executor_label>/interchange.log`. The base directory should be passed by the executor via kwargs to the interchange starter. For eg. HTEX does this `"logdir": "{}/{}".format(self.run_dir, self.label),`
in the starter, which is then used by the Interchange.

**Comment by benclifford** [comment]
low latency executor is abandoned - closing
