### ISSUE TITLE
EXEX on Slurm: the ntasks-per-node is always 1 in the submit script

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#745]
`ntasks-per-node` is always 1 in the submit script.
mpi_worker_pool will return error below because they cannot launch more than 1 task on each node.

```There are not enough slots available in the system to satisfy the 5 slots
that were requested by the application:
  mpi_worker_pool.py

Either request fewer slots for your application, or make more slots available
for use.```

**Comment by macintoshpie** [comment]
I think I'm facing a similar issue with htex and Torque.
Torque will always request ppn=1 due to htex
https://github.com/Parsl/parsl/blob/2791a8f80f6b1ec7608d15b94fe34cee0c52a3dd/parsl/executors/high_throughput/executor.py#L470
https://github.com/Parsl/parsl/blob/2791a8f80f6b1ec7608d15b94fe34cee0c52a3dd/parsl/providers/torque/template.py#L7

**Comment by benclifford** [comment]
crossreference #669 which seems similar (but different provider/executor)

**Comment by benclifford** [comment]
exex is EOL - closing
