### ISSUE TITLE
TorqueProvider timeout with qstat and qsub commands

### ISSUE THREAD

**Issue by macintoshpie** [Parsl/parsl#755]
I've experienced timeouts by the TorqueProvider on NSCC. Specifically, it's timing out when executing the `qstat` [command](https://github.com/Parsl/parsl/blob/fa1977937cde63f5fb3f6463affd5c116410b235/parsl/providers/torque/torque.py#L114) in and `qsub` [command](https://github.com/Parsl/parsl/blob/fa1977937cde63f5fb3f6463affd5c116410b235/parsl/providers/torque/torque.py#L204) (haven't checked `qdel` in `cancel()`

Probably need to remove the wait time from these calls to allow use of `cmd_timeout` property of ClusterProvider.

**Comment by benclifford** [comment]
I've experienced issues before with cluster providers where similar status commands took a long time rather than hanging, and did some similar sounding timeout hacking.

I'd like to just be clear if that is the situation that you are experiencing? For example, if you run qstat in a shell, how many seconds does it take to run?

**Comment by yadudoc** [comment]
Fixed by #768
