### ISSUE TITLE
SlurmProvider submit fails on Windows 10 due to DOS linefeed chars

### ISSUE THREAD

**Issue by etatara** [Parsl/parsl#833]
I'm using SlurmProvider to submit a job on a remote linux cluster from a Windows client machine and the default python file open behavior is injecting DOS style linefeed chars '\r\n' in the submit script which slurm doesn't handle, and fails.  This occurs on Windows 10 with python 3.7.  

SlurmProvider works if I change the cluster_provider.py _write_submit_script() to use the newline arg as follows:

with open(script_filename, 'w', newline='\n') as f:

I'm wondering if there's a less hackish way to approach this?  Redefining the python builtin open() doesn't help.

**Comment by yadudoc** [comment]
Hi @etatara, We haven't had many users running Parsl from Windows environment so we don't officially support or test on Windows. Since most cluster scheduler systems would be linux environments, I suspect that updating the `_write_submit_script()` method to explicitly use `\n` as you have pointed out is a reasonable fix.

Thanks for reporting this issue. If you are up for it, I'd encourage you to submit a pull request with the change and we could have it merged into the next release.

**Comment by yadudoc** [comment]
Let's close this issue, and re-open if there's anything unresolved.
