### ISSUE TITLE
Asynchronous Failure from Bash App Function

### ISSUE THREAD

**Issue by meschw04** [Parsl/parsl#948]
Suppose I submit a Parsl script with four bash app functions running in parallel on ALCF Theta. Suppose my first bash app function errors out. Will it cut off the progress of the other tests? Or will each of them run asynchronously and either complete or also error out? In other words, once one of the function hits a fatal error, will it kill progress on the other functions?

It appears this may be what happened for me. Any thoughts on how to fix that?

Yadu also mentioned that it is likely the case that the default behavior of the scheduler is to shut down if any aprun failed, and that there may be a workaround for this.

**Comment by yadudoc** [comment]
Hi Marcus, Could you try adding a -C flag to the aprun command in your app script ?

It is possible that if a task launched with aprun fails on a worker, that worker may not be able launch another aprun task to fill that slot. I've seen something vaguely reminiscent. This may not matter to you since you are not re-using workers for now. Just something to keep in mind.

**Comment by meschw04** [comment]
Hi @yadudoc ,
I was in the queue all yesterday, can try that again today with the '-C' flag.
One other observation from my latest run. It appears that one of the four processes finished long before the other tree did. When that one finished, it looks like it ended all of the other tasks in progress. Will the -C flag also help resolve that, the same that it would if one of the tasks generates an error?
Thanks,
Marcus

**Comment by meschw04** [comment]
So after rerunning with the '-C' flag on all of the aprun commands, it appears that everything went pretty well. I think that's solved the problem for now. Thanks!
