### ISSUE TITLE
Make a local config that can be loaded

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#96]
I think its confusing to have two different ways to instantiate the DFK. I think we should do away with the shorthand way and instead push people towards using config objects. The easiest way would be to include a local config in the Parsl package that could be imported. 

E.g., from parsl.config import local_config

**Comment by yadudoc** [comment]
In the latest parsl, we now have a configs module that can be expanded to support a curated set of sites.

```
from parsl.configs.local import localThreads
from parsl.configs.local import localIPP
```
The above works in the parsl master branch.

The drawback here is that we are provider whole configs that contain a single site, rather than a method
that pulls together multiple sites into a one config. This is what I think makes most sense:
```
from parsl.configs import configBase
from parsl.sites import localThreads, coriRemote, thetaRemote
configBase['sites'] = [localThreads, coriRemote, thetaRemote]
```

I think this would make the config more composable, but I'm not entirely sure how many users would want/use multi-site configs.

**Comment by mjwilde** [comment]
I think perhaps this becomes simpler and more manageable if we process
config docs via code instead of importing them?

*MICHAEL WILDE*

*Parallel Works Inc. <http://www.parallelworks.com>*

wilde@parallelworks.com
*m* +1 708 203 9548

**Comment by yadudoc** [comment]
@kylechard If you think the local configs are okay can we close this one ? I think standardizing site configs, and allowing users to combine sites is going to take more design that we should defer until we have more user input. 

@mjwilde We are treating configs as code/datastructures that can be imported, modified etc. I suspect that I might be misunderstanding your comment.

**Comment by benclifford** [comment]
This appears to have been unwound in 49d9594b2d6ac782a9edf4776c4521db9133a622
