### ISSUE TITLE
Make travis skip doc changes

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#986]

**Comment by benclifford** [comment]
I would prefer that travis tests the doc build so that we can attempt avoid things like the 0.8 docs being apparently unbuildable.

I think some frustrations leading to this issue #986 have been addressed in other ways:

CI is now much faster than it was (approximately 3x speedup, with potential another factor of 2 when #1228 is addressed)

CI also runs much more rarely - only on PRs, rather than on every push to a branch.

The above two changes have substantially reduced queue length in CI; and at heart this issue stems from "make the CI not use up expensive time when we know it won't detect anything different".

**Comment by annawoodard** [comment]
Agreed, closing
