### ISSUE TITLE
Implement time limits for python apps

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#998]
Requested by @lgray.

**Comment by yadudoc** [comment]
I've got a quick and dirty solution for this here: https://gist.github.com/yadudoc/d9dedc4ea447b1cc1cc82846cc98fd40

Essentially this would give you a `@timeout` decorator, that you can use like this : 
```python
@python_app
@timeout
def sleeper(x, timeout=None):
    """ Timeout must be passed as a kwarg at function call time
    """
    import time
    time.sleep(x)
    return x

sleeper(10, timeout=2).result()
```

**Comment by yadudoc** [comment]
As reported by @annawoodard this method can result in the worker getting killed by the interrupts, and needs more work in order to be useful.

@jchiang87 also request this feature for debugging an issue with python apps.

**Comment by benclifford** [comment]
Using process-wide alarms rather than something restricted to the scope of the actual executing app is probably going to never work right.

There is this awful hack which lets you fire an asynchronous exception into an arbitrary thread, which could probably be used as long as you were sure of the thread executing the app. https://gist.github.com/liuw/2407154

**Comment by annawoodard** [comment]
Cross ref: CoffeaTeam/coffea#131

**Comment by annawoodard** [comment]
@jchiang87 @lgray Note python time limits are now supported. You can enable this feature by adding a `walltime` keyword arg to your python app.
